### ISSUE TITLE
Add headline caching to the scraper

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#8]
Inconsistently throws `list index out of bounds` error for unknown reasons.

**Comment by shobrook** [comment]
The index out of bounds error occurs very infrequently and can be handled with a simple try/except.

**Comment by alichtman** [comment]
Next step on this is to combine the files scraped by scraper.py into a single headlines_data.csv file, and then to call the scraper function in main (should have thrown that in the last commit, my b. We'll hit this next round).

**Comment by shobrook** [comment]
Instead of re-scraping the entire blockchain and OHLCV datasets, we could pull the timestamp of the most recent row in each dataset and use that to specify a date range (timestamp + 1 to present time) in our API calls. Then, the portion of the dataset each call returns could be concatenated with the original "cached" CSV that it belongs to.

We also need to add similar functionality to the headline scraper, where we read the timestamp of the most recent row in each dataset and use that to specify a date range for our scraper. Then, we'll append the newly scraped headlines to their respective CSVs.
